import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Header />
     <Nav />
     <Results />
    </div>
  );
}

//server side rendering for this page alone:
// this function will get executed befor the upper part of this
// page will be rended to the screen
// the server render happens first, and than the information is
//send to the client 

export async function getServerSideProps(context) {
  //we pull the genre from the url
  const genre = context.query.genre;
}

// GENERATE API KEY
//in order to gat the TMDb API_KEY we rejister --> enter profile --> 
// settings --> API --> filling personal details --> retrieve the API(v3 auth)
// --> a16ece7611813bc6e673304cb9fb966f --> past it in the .anv.local
// once we have done this, we start the run again: "yarn rud dev" or: "yarn run" and than "dev"
// we want to see that it is loaded by getting:
// "info  - Loaded env from C:\Users\arbiv\Dropbox\My PC (LAPTOP-LHMU0K3R)\Desktop\hulu2\.env.local"

